Diagnostics:
  ClangTidy:
    Add:
      [
        performance-*,
        bugprone-*,
        portability-*,
        modernize-*,
        google-*,
        misc-*,
        bugprone-*,
        readability-*,
      ]
    Remove: modernize-use-trailing-return-type
    CheckOptions:
      WarnOnFloatingPointNarrowingConversion: false
      readability-identifier-naming.NamespaceCase          : lower_case 
      readability-identifier-naming.ClassCase              : CamelCase  
      readability-identifier-naming.StructCase             : CamelCase  
      readability-identifier-naming.TemplateParameterCase  : CamelCase  
      readability-identifier-naming.FunctionCase           : aNy_CasE  
      readability-identifier-naming.VariableCase           : lower_case 
      readability-identifier-naming.ClassMemberCase        : lower_case 
      readability-identifier-naming.ClassMemberSuffix      : _          
      readability-identifier-naming.PrivateMemberSuffix    : _          
      readability-identifier-naming.ProtectedMemberSuffix  : _          
      readability-identifier-naming.EnumConstantCase         : CamelCase 
      readability-identifier-naming.EnumConstantPrefix       : k         
      readability-identifier-naming.ConstexprVariableCase    : CamelCase 
      readability-identifier-naming.ConstexprVariablePrefix  : k         
      readability-identifier-naming.GlobalConstantCase       : CamelCase 
      readability-identifier-naming.GlobalConstantPrefix     : k         
      readability-identifier-naming.MemberConstantCase       : CamelCase 
      readability-identifier-naming.MemberConstantPrefix     : k         
      readability-identifier-naming.StaticConstantCase       : CamelCase 
      readability-identifier-naming.StaticConstantPrefix     : k         
      readability-implicit-bool-conversion.AllowIntegerConditions  : 1   
      readability-implicit-bool-conversion.AllowPointerConditions  : 1   

